.phony: all

all: small medium large

small:	
	@echo small problem
	julia src/knapsack01.jl data/small.txt out/small.txt

medium: 
	@echo medium problem
	julia src/knapsack01.jl data/medium.txt out/medium.txt
	
large: 
	@echo large problem
	julia src/knapsack01.jl data/large.txt out/large.txt

