.phony: all

all: small medium large

small:
	@echo
	@echo small problem
	julia src/addmergekill.jl data/small.txt

medium:
	@echo
	@echo medium problem
	julia src/addmergekill.jl data/medium.txt

large:
	@echo
	@echo large problem
	julia src/addmergekill.jl data/large.txt

