.phony: run

run:
	@echo
	@echo small problem
	julia src/knapsack01.jl data/small.txt out/small.txt
	@echo
	@echo medium problem
	julia src/knapsack01.jl data/medium.txt out/medium.txt
	@echo
	@echo large problem
	julia src/knapsack01.jl data/large.txt out/large.txt

